### ISSUE TITLE
no exe

### ISSUE THREAD

**Issue by sn1pes** [tiagorlampert/CHAOS#24]
after i installed the new release, chaos no longer generates exe only generates the source i.e filename.go and no longer generates filename.exe
is just me or other people are getting the same error. initially i it happened in my backbox. so i felt perhaps it's the root privilege thing. so i started up my kali and met with with the same issue. can
 you kindly look into in it please please.
final request, i just watched your youtube official video of the newly released chaos and watching keenly i observed the keylogger can't does not log the visited site, it only logs credential also kindly do fix it to log visited site in order to  make the grabbed credential more useful. thank very much for such a wonderful & truly undetectable product

**Comment by tiagorlampert** [comment]
Hello,
Check if you have the dependencies to compile, if it are not installed you can't compile the .EXE file.
Check out: https://github.com/tiagorlampert/CHAOS#how-to-use

To install the dependencies, Run on terminal:
```
go get github.com/kbinani/screenshot && go get github.com/lxn/win
go install github.com/kbinani/screenshot && go install github.com/lxn/win
```
Maybe you will see the message "package github.com/lxn/win: build constraints exclude all Go files".
It's occurs because the libraries are to windows systems, but it necessary to build the payload.

About the keylogger function i'll working to make it better. There are some things than i don't know how to implement, but i'll keep trying.

**Comment by sn1pes** [comment]
hi, i thanks but before i upgraded to this new release i didn't have the go or path installed but it worked just fine perhaps it's the new features that now warrants that the go be installed but i will try to fix the install cause i got the "package github.com/lxn/win: build constraints exclude all Go files" error. will try to fix the install. thank you
