### ISSUE TITLE
execuse me,Can the project run  under ubuntu 16.04 server? 

### ISSUE THREAD

**Issue by pythonone** [tiagorlampert/CHAOS#26]
I have not generate exe. the project need other library ?

**Comment by tiagorlampert** [comment]
Hello, i've never tested on Ubuntu 16.04, but probably yes it runs.
Check if you have the dependencies to compile, if it are not installed you can't compile the .EXE file.
Check out: https://github.com/tiagorlampert/CHAOS#how-to-use

To install the dependencies, Run on terminal:
```
go get github.com/kbinani/screenshot && go get github.com/lxn/win
go install github.com/kbinani/screenshot && go install github.com/lxn/win
```
Maybe you will see the message _"package github.com/lxn/win: build constraints exclude all Go files"_.
It's occurs because the libraries are to windows systems, but it necessary to build the payload.

**Comment by pythonone** [comment]
thank you ,it is my fault 。I used golang for the first time, you make me have a strong disire to  study golang for penetration test

**Comment by tiagorlampert** [comment]
Great! For some things golang is a good alternative. =D
