### ISSUE TITLE
build constraint error

### ISSUE THREAD

**Issue by sn1pes** [tiagorlampert/CHAOS#28]
hello 
i was wondering how you correctly set your gopath environment variables working, i have tried many times to run the below command in order to get golang dependencies correctly installed but to no avail.
1 go get github.com/kbinani/screenshot && go get github.com/lxn/win
2 go install github.com/kbinani/screenshot && go install github.com/lxn/win
at first i set the path in the .profile like this
export GOPATH=/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
the it gave me this error message
can't load package: package github.com/lxn/win: build constraints exclude all Go files in /root/go/src/github.com/lxn/win
i edited and removed (export GOPATH=/go) from the .profile it still gave me the same error. i edited again and removed the ( :$GOPATH/bin) it gave me the same error
i edited again for the last time and like this export (export PATH=$PATH:/usr/local/go/bin)
still getting the same error. i followed all the instruction from the golang site. how can i successfully fix that error.

**Comment by tiagorlampert** [comment]
Hello,
I use the default gopath environment variables.

The message _"package github.com/lxn/win: build constraints exclude all Go files"_, occurs because the libraries are to windows systems, but they are necessary to build the payload. So you need to get it anyway.

This error is described in https://github.com/tiagorlampert/CHAOS#how-to-use
> Maybe you will see the message "package github.com/lxn/win: build constraints exclude all Go files".
> It's occurs because the libraries are to windows systems, but it necessary to build the payload.

So even with this error be showed the CHAOS will build the payload.
Could you try again and send me feedback?!

**Comment by krishnenduash** [comment]
work fine... bro
